arch: "conv_strided"
batch_per_gpu: 512
lr: 0.01
num_workers: 16
transform: "standard"
n_epochs: 100
save_top_k: 5
logdir: "experiments"
data_root: "/data/.cache/datasets/MAIC2020"
use_ext: false
single_ch: true
focal_loss: false
ensemble_infer: false
