arch: "conv1d_r34_nl4"
batch_per_gpu: 512
lr: 0.0001
num_workers: 16
transform: "offset"
n_epochs: 30
save_top_k: 5
logdir: "experiments"
data_root: "/data/.cache/datasets/MAIC2020"
use_ext: false
single_ch: true
focal_loss: true
ensemble_infer: false
