arch: "conv1d_r50_nl5"
batch_per_gpu: 512
lr: 0.0001
num_workers: 16
transform: "standard"
n_epochs: 30
save_top_k: 5
logdir: "experiments"
data_root: "/data/.cache/datasets/MAIC2020"
use_ext: false
single_ch: false
focal_loss: true
ensemble_infer: false
