arch: "transformer_basic"
batch_per_gpu: 512
lr: 0.1
num_workers: 16
transform: "offset"
n_epochs: 100
save_top_k: 5
logdir: "experiments"
data_root: "/data/.cache/datasets/MAIC2020"
use_ext: false
single_ch: false
focal_loss: true
ensemble_infer: true
